version: '4.16'
services:
  app:
    container_name: app
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27217"
    volumes:
      - "./data:/data/db"